server:
  port: 8070

spring:
  application:
    name: server-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #zipkin
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
    service:
      name: server-provider
  sleuth:
    sampler:
      probability: 1
