spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: server-consumer
server:
  port: 8080
  #zipkin
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
    service:
      name: server-consumer
  sleuth:
    sampler:
      probability: 1
